/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kaninfurlowmysql;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Kanin
 */
public class MySQL extends javax.swing.JFrame {

    /**
     * Creates new form MySQL
     */
    public MySQL() {
        initComponents();
    }

    class BadInputException extends Exception {

        String s;

        BadInputException(String s) {
            this.s = s;

        }

        public String toString() {
            return s;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGender = new javax.swing.ButtonGroup();
        bgClass = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chkHuman = new javax.swing.JCheckBox();
        chkElf = new javax.swing.JCheckBox();
        chkVampire = new javax.swing.JCheckBox();
        chkAlien = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rdoWarrior = new javax.swing.JRadioButton();
        rdoRogue = new javax.swing.JRadioButton();
        rdoRanger = new javax.swing.JRadioButton();
        rdoCleric = new javax.swing.JRadioButton();
        lblPicture = new javax.swing.JLabel();
        lblPicName = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        btnAddCharacter = new javax.swing.JButton();
        btnChooseImage = new javax.swing.JButton();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MySQL");

        jLabel1.setText("Name:");

        jLabel2.setText("Birthday:");
        jLabel2.setToolTipText("yyyy/mm/dd");

        jLabel3.setText("Weight:");

        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtBirthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtWeight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Race");

        chkHuman.setText("Human");

        chkElf.setText("Elf");

        chkVampire.setText("Vampire");

        chkAlien.setText("Alien");

        jLabel5.setText("Gender");

        bgGender.add(rdoMale);
        rdoMale.setSelected(true);
        rdoMale.setText("Male");

        bgGender.add(rdoFemale);
        rdoFemale.setText("Female");

        jLabel6.setText("Class");

        bgClass.add(rdoWarrior);
        rdoWarrior.setSelected(true);
        rdoWarrior.setText("Warrior");

        bgClass.add(rdoRogue);
        rdoRogue.setText("Rogue");

        bgClass.add(rdoRanger);
        rdoRanger.setText("Ranger");

        bgClass.add(rdoCleric);
        rdoCleric.setText("Cleric");

        lblPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnView.setText("View Data");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAddCharacter.setText("Add Character");
        btnAddCharacter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCharacterActionPerformed(evt);
            }
        });

        btnChooseImage.setText("Choose Image");
        btnChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseImageActionPerformed(evt);
            }
        });

        lblError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(24, 24, 24)
                                                        .addComponent(txtWeight))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(31, 31, 31)
                                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                                                .addComponent(jLabel4)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkAlien)
                                    .addComponent(chkHuman)
                                    .addComponent(chkElf)
                                    .addComponent(chkVampire))
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdoFemale)
                                            .addComponent(rdoMale)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdoRogue)
                                            .addComponent(rdoWarrior)
                                            .addComponent(rdoRanger)
                                            .addComponent(rdoCleric))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPicture, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblPicName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnView)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddCharacter)
                        .addGap(18, 18, 18)
                        .addComponent(btnChooseImage)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(chkHuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkElf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkVampire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAlien)
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPicName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rdoMale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoFemale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoWarrior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoRogue)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoRanger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoCleric)))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnAddCharacter)
                    .addComponent(btnChooseImage))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        try {
            new View().setVisible(true);
            new MySQL().setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MySQL.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnViewActionPerformed
    static File file;
    private void btnAddCharacterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCharacterActionPerformed
        String mySQLURL = "jdbc:mysql://cstnt.tstc.edu:3306/furlowksp21";
        String userName = "furlowksp21";
        String password = "temp";

        Connection con = null;
        Statement stmt = null;

        try {
            System.out.println("Connecting to database...");
            con = DriverManager.getConnection(mySQLURL, userName, password);
            System.out.println("Connection: " + con.isValid(0));
        } catch (Exception ex) {
            System.out.println("Error: " + ex.toString());
        }

        //creating table in database
        try {
            DatabaseMetaData dbm = con.getMetaData();
            ResultSet tables = dbm.getTables(null, null, "Profile", null);

            if (!tables.next()) {
                stmt = con.createStatement();
                String sql = "CREATE TABLE PROFILE "
                        + "(name VARCHAR(30), "
                        + "birthday DATE, "
                        + "weight DECIMAL, "
                        + "gender BOOLEAN, "
                        + "class ENUM('Warrior', 'Rogue', 'Ranger', 'Cleric'), "
                        + "race VARCHAR(60), "
                        + "img longBLOB)";

                stmt.executeUpdate(sql);
                System.out.println("Table created.");
            }

        } catch (Exception e) {
            System.out.println("Error Creating Table... " + e.toString());
        }

        String race, human = "Human", elf = "Elf", vampire = "Vampire", alien = "Alien";
        String temp = "", temp1 = "", temp2 = "", temp3 = "";

        if (chkHuman.isSelected()) {
            temp = human;
        }

        if (chkElf.isSelected()) {
            temp1 = elf;
        }

        if (chkVampire.isSelected()) {
            temp2 = vampire;
        }

        if (chkAlien.isSelected()) {
            temp3 = alien;
        }
        race = temp + temp1 + temp2 + temp3;
        boolean bMale = false, bFemale = false;

        if (rdoMale.isSelected()) {
            bMale = true;
        } else {
            bFemale = true;
        }

        String classType, name, birthday, weight;

        if (rdoWarrior.isSelected()) {
            classType = rdoWarrior.getText();
        } else if (rdoRogue.isSelected()) {
            classType = rdoRogue.getText();
        } else if (rdoRanger.isSelected()) {
            classType = rdoRanger.getText();
        } else {
            classType = rdoCleric.getText();
        }

        name = txtName.getText();
        birthday = txtBirthday.getText();
        weight = txtWeight.getText();
        

        try {
            
            String tempName = name.replace(" ", "");
            
            for (int i = 0; i < tempName.length(); i++) {
                if (!Character.isLetter(tempName.charAt(i))) {
                    throw new BadInputException("Name must be all letters");
                }
            }

            if (name.contains("  ")) {
                throw new BadInputException("Name cannot have more than 1 space");
            }
 
            double tempWeight = Double.parseDouble(weight);
            
            
            
        } catch (BadInputException e) {
            lblError.setText(e.toString());
        } catch (NumberFormatException ex) {
            lblError.setText(ex.toString());
        }catch(Exception ex){
            lblError.setText(ex.toString());
        }

        

        try {
            byte[] b = Files.readAllBytes(file.toPath());
            String statement = "insert into Profile values(?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(statement);
            ps.setString(1, name);
            ps.setString(2, birthday);
            ps.setString(3, weight);
            ps.setBoolean(4, bMale);
            ps.setString(5, classType);
            ps.setString(6, alien);
            ps.setBinaryStream(7, new ByteArrayInputStream(b, 0, b.length));
            int n = ps.executeUpdate();
            System.out.println(n + " rows effected");

        } catch (SQLException ex) {
            System.out.println(ex.toString());
        } catch (IOException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btnAddCharacterActionPerformed


    private void btnChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseImageActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");
            fileChooser.setFileFilter(extensionFilter);
            int select = fileChooser.showOpenDialog(null);

            String getImage;

            if (select == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
                BufferedImage buffImage = ImageIO.read(file);
                getImage = file.getName();
                lblPicture.setIcon(new ImageIcon(buffImage.getScaledInstance(lblPicture.getWidth(), lblPicture.getHeight(), 0)));
                lblPicName.setText(getImage);
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.toString());
        }
    }//GEN-LAST:event_btnChooseImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MySQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MySQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgClass;
    private javax.swing.ButtonGroup bgGender;
    private javax.swing.JButton btnAddCharacter;
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnView;
    private javax.swing.JCheckBox chkAlien;
    private javax.swing.JCheckBox chkElf;
    private javax.swing.JCheckBox chkHuman;
    private javax.swing.JCheckBox chkVampire;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblPicName;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JRadioButton rdoCleric;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JRadioButton rdoRanger;
    private javax.swing.JRadioButton rdoRogue;
    private javax.swing.JRadioButton rdoWarrior;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
